### PR TITLE
build: Initializing frappe template

### PR DESCRIPTION
**Pull request by gavindsouza**
Changes I made to the source while attempting to use frappix by following https://blaggacao.github.io/frappix/use-templates.html

> [!WARNING]
> Potentially bad suggestions in this PR

### CODE REVIEW

**Comment by blaggacao** [comment]
LGTM, thanks!

**Comment by gavindsouza** [comment]
@blaggacao Did you force push this out of existence from `main`?

**Comment by blaggacao** [comment]
Oh. Possibly :facepalm:

Yeah, while trying to fix CI baseline. Sry!

**Comment by blaggacao** [comment]
It's back

**Pull request merged**
